kind: Deployment
apiVersion: apps/v1

metadata:
  name: devices-simulator

spec:
  replicas: 1
  selector:
    matchLabels:
      app: devices-simulator
  template:
    metadata:
      labels:
        app: devices-simulator
    spec:
      containers:
        - name: devices-simulator
          image: mcr.microsoft.com/oss/azure-samples/azureiot-telemetrysimulator:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: EventHubConnectionString
              value: EVENT_HUB_CONNECTION_STRING_PLACEHOLDER
            - name: DeviceList
              value: 'device-01,device-42' # Specify your device names
            - name: MessageCount
              value: '0' # send unlimited
            - name: Interval
              value: '1000'
            - name: Template
              value: '{"deviceId": "$.DeviceId", "deviceTimestamp": "$.Time", "temp": $.DoubleValue}'
            - name: Variables
              value: '[{"name": "DoubleValue", "randomDouble":true, "min":20.00, "max":28.00}]'
